name: Button
status: ready
collated: false
context:
  text: 'Regular button'
  icon: null
  link: '#'
  classes: []
handle: button

variants:
  - name: xs
    label: "Size: XS"
    context:
      classes: ['button--xs']
      text: 'An teeny tiny button'

  - name: small
    label: "Size: Small"
    context:
      classes: ['button--sm']
      text: 'Smol button'

  - name: large
    label: "Size: Large"
    context:
      classes: ['button--lg']
      text: 'A big button'

  - name: xl
    label: "Size: XL"
    context:
      classes: ['button--xl']
      text: 'Huge button!'
    notes: "<strong>Avoid:</strong> There's probably never any need for this, it really is probably too big for almost all applications"

  - name: pointy
    label: "Style: Pointy"
    context:
      classes: ['button--pointy']
      text: 'Button with pointy arrow'

  - name: cutout
    label: "Style: Clipped"
    status: wip
    context:
      classes: ['button--clipped']
      text: 'Button with clipped corner (experimental!)'

  - name: cutout-ldn
    label: "Style: Clipped (LDN)"
    status: wip
    context:
      classes: ['button--clipped']
      text: 'Button with clipped corner (experimental!)'
    preview: '@preview-ldn'

  - name: caps
    label: "Style: Caps"
    context:
      classes: ['button--caps']
      text: 'Button with uppercase/caps: note this poses accessibility concerns - avoid long copy'
    notes: '<strong>NB:</strong> This poses accessibility concerns - avoid long copy'


  - name: slate
    label: "Color: Slate"
    context:
      classes: ['button--slate']
      text: 'Slate Coloured Button'

  - name: outline
    label: "Style: Outline"
    context:
      classes: ['button--outline']
      text: 'Outline Style Button'

  - name: outline-slate
    label: "Style: Outline Slate"
    context:
      classes: ['button--outline-slate']
      text: 'Slate Outline Style Button'
