name: Title
status: ready
collated: false
context:
  text: 'This is a title'
  background: []
  modifiers: []
  animate: false
handle: title

variants:

  - name: default with tail
    label: "Default (with tail)"
    context:
      modifiers: ['has-tail']
      text: 'This is a highlighted title with a tail'

  - name: white
    label: "White"
    context:
      background: white
      text: 'This is a white highlighted title'

  - name: white with tail
    label: "White (with tail)"
    context:
      tail: true
      background: white
      text: 'This is a white highlighted title with a tail'

  - name: slate
    label: "Slate"
    context:
      background: slate
      text: 'This is a slate highlighted title'

  - name: slate with tail
    label: "Slate (with tail)"
    context:
      tail: true
      background: slate
      text: 'This is a slate highlighted title with a tail'

  - name: maroon
    label: "Maroon"
    context:
      background: maroon
      text: 'This is a maroon highlighted title'

  - name: maroon with tail
    label: "Maroon (with tail)"
    context:
      tail: true
      background: maroon
      text: 'This is a maroon highlighted title with a tail'

  - name: pink
    label: "Pink"
    context:
      background: pink
      text: 'This is a pink highlighted title'

  - name: pink with tail
    label: "Pink (with tail)"
    context:
      tail: true
      background: pink
      text: 'This is a pink highlighted title with a tail'


  - name: examples
    label: "Examples"

  - name: ldn-examples
    label: "Examples (LDN)"
    preview: '@preview-ldn'
